[workspace]
members = [
  "cpu_timer_guess_freq",
  "generator",
  "haversine",
  "json",
  "parser",
  "platform_metrics",
  "timing_macro",
]
exclude = []
resolver = "3"

[workspace.package]
version = "0.1.0"
authors = ["Austin Rooks"]
description = "haversine"
