[package]
name = "parser"
edition = "2024"
version.workspace = true
authors.workspace = true
description.workspace = true

[dependencies]
clap = { version = "4.5.41", features = ["derive"] }
haversine = { path = "../haversine" }
json = { path = "../json" }
